"""init: calendar_epochs, holy_days, national_holidays, adhikamasa_years

Revision ID: 7d3bc934fdcd
Revises: 
Create Date: 2026-06-03 07:45:21.162821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3bc934fdcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adhikamasa_years',
    sa.Column('cs_year', sa.Integer(), nullable=False),
    sa.Column('be_year', sa.Integer(), nullable=False),
    sa.Column('ce_year', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cs_year')
    )
    op.create_index(op.f('ix_adhikamasa_years_be_year'), 'adhikamasa_years', ['be_year'], unique=False)
    op.create_index(op.f('ix_adhikamasa_years_ce_year'), 'adhikamasa_years', ['ce_year'], unique=False)
    op.create_table('calendar_epochs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_label', sa.String(length=50), nullable=False),
    sa.Column('ce_year', sa.Integer(), nullable=False),
    sa.Column('be_year', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('image_caption', sa.String(length=200), nullable=True),
    sa.Column('image_credit', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_epochs_ce_year'), 'calendar_epochs', ['ce_year'], unique=False)
    op.create_table('holy_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('waxing', sa.Boolean(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('national_holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('national_holidays')
    op.drop_table('holy_days')
    op.drop_index(op.f('ix_calendar_epochs_ce_year'), table_name='calendar_epochs')
    op.drop_table('calendar_epochs')
    op.drop_index(op.f('ix_adhikamasa_years_ce_year'), table_name='adhikamasa_years')
    op.drop_index(op.f('ix_adhikamasa_years_be_year'), table_name='adhikamasa_years')
    op.drop_table('adhikamasa_years')
    # ### end Alembic commands ###
